### ISSUE TITLE
The Egocentric Police Dick skin is immune to headshots. 

### ISSUE THREAD

**Issue by SilvaStars** [redsunservers/LoadoutBugTracker#195] opened 2018-03-15 02:41 UTC
Found this out on combat surf when trying to snipe in the arena, where I headshotted wo and noticed that he didn't die from the headshot. After testing it a bit, we are certain the skin gives spy immunity to headshots. Evidence: [https://gfycat.com/GrizzledDazzlingKusimanse](https://gfycat.com/GrizzledDazzlingKusimanse) EDIT: went to maverick after and was able to headshot wo just fine, Dunno if that means its server specific, or gamemode specific.

**Comment by EgocentricPoliceDick** [comment] 2018-03-15 02:44
This is an issue with hitbox configuration. Last I checked, head hitboxes were defined on the models.
However, I'm currently applying some fixes for other things in the new models, so let me double check that these are working as intended.

**Comment by EgocentricPoliceDick** [comment] 2018-03-15 02:48
...and from the staff discord:

```
[02:46] Kirillian: They are
[02:46] Kirillian: Hitboxes are fixed
[02:47] Kirillian: If someone says otherwise they are bsing
[02:47] Kirillian: I added hitboxes since the start
[02:47] Kirillian: You can check in hlmv even
```

**Comment by EgocentricPoliceDick** [comment] 2018-03-15 02:52
Word back says that the specific map you were on has in-game logic which can cause the player to survive instant-kills such as headshots. Can you test on a map which you know for sure doesn't have this? @SilvaStars

**Comment by EgocentricPoliceDick** [comment] 2018-03-15 02:54
Next time please leave a reply, not an edit. I'll get a notification since I'm assigned to the ticket.
I'll close this out now.

**Closed by EgocentricPoliceDick** 2018-03-15 02:54 UTC
Labels: closed:invalid, source:server-general
