### ISSUE TITLE
Freeze tag arena round doesn't end despite enemy team being completely frozen

### ISSUE THREAD

**Issue by bwauts** [redsunservers/LoadoutBugTracker#137] opened 2017-12-25 20:08 UTC
![image](https://user-images.githubusercontent.com/33851923/34342685-4758f990-e96c-11e7-9b2d-0c61461d8890.png)

**Comment by EgocentricPoliceDick** [comment] 2017-12-25 20:27
iirc darth made a change to koth which prevented a full freezeout causing a round win

**Comment by ramunecarbonated** [comment] 2017-12-25 20:27
this is arena, not koth, don't assign this to me.

**Comment by EgocentricPoliceDick** [comment] 2017-12-25 20:29
i am saying that the change might not have stuck to koth only

**Comment by ramunecarbonated** [comment] 2017-12-25 20:29
koth and arena are completely different things in the freezetag config, besides that freezetag is completely stock and we don't seem to have a repo for it.

**Comment by EgocentricPoliceDick** [comment] 2017-12-25 20:34
we don't? what the fuck i swear we had one
nevermind i'll quickly conjure one up

**Comment by ramunecarbonated** [comment] 2018-01-09 10:33
Here is the line in question confirming that it is set correctly for Arena.

Closing as no other incidents have been reported since. Comment in case it does happen again.

```
"arena_"
{
	"eliminations"     "1"
```

**Comment by woisalreadytaken** [comment] 2018-01-09 21:04
@ramunecarbonated the issue is happening because all arena maps in the freeze tag rotation are workshop maps, and the config doesn't seem to support that (we played on a stock arena map and it worked fine, shoutout to blotz for letting me test this)

**Comment by koopa516** [comment] 2018-01-09 21:07
I'm on it

**Comment by koopa516** [comment] 2018-01-09 21:12
Fixed

**Closed by koopa516** 2018-01-09 21:12 UTC
Labels: source:gamemode, type:bug
