### ISSUE TITLE
SZF: having the Rocket Jumper equipped gives 62 reserve ammo for all rocket launcher pickups

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#117] opened 2017-12-18 05:26 UTC
affects everything (stock, liberty launcher, etc.)

was unable to test if it also happens with the sticky jumper

**Comment by FortyTwoFortyTwo** [comment] 2017-12-18 16:25
Can confirm the sticky jumper also gives 72 ammo,

Also if I remembered correctly, if you equip any 150 ammo syringe gun, then picks up crossbow gives you 150 ammo crossbow. Will have to check again just to make sure i'm correct.

**Comment by ramunecarbonated** [comment] 2017-12-18 16:28
Heya sorry for my late reply, I know the cause and it is because of how TF2 is treating the weapon's maximum ammo. I will mark this issue as appropriate when Snow Sniffer is successfully launched.

**Comment by ramunecarbonated** [comment] 2017-12-18 22:42
This issue is quite complicated to fix, so if it works it works, if not then I will be in for quite a fun ride.

**Comment by itVictor** [comment] 2017-12-20 20:51
@ramunecarbonated bumping as it isn't fixed/uploaded for the sticky jumper/crossbow, but the rocket jumper is fixed.
I would like to add that for the crossbow the bug happens if you pickup a syringe gun and then pickup the crossbow, if you have the crossbow equipped normally (in your tf2 loadout) the bug still occurs.

**Comment by ramunecarbonated** [comment] 2017-12-21 08:24
@koopa516 @Benoist3012 
For this issue, this is an ammo issue and I honestly have no idea how this bug appeared in the first place.

**Comment by itVictor** [comment] 2018-01-03 22:11
adding to say that the bug also happens with rescue ranger pickups, if you have a shotgun equipped you get 32 reserve ammo instead of 16

**Comment by Benoist3012** [comment] 2018-01-04 10:45
The issue there is pretty simple. The max ammo is wrongly calculated, the m_iAmmo netprop isn't properly updated when picking up different weapons. its value is based on the last weapon that updated m_iAmmo, and since only the game does that and not SZF you can quickly mess up every wep ammo.
Anyways, I'll deploy a fix soon.

**Comment by Benoist3012** [comment] 2018-01-04 15:52
Fixed, thanks for report.

**Closed by Benoist3012** 2018-01-04 15:52 UTC
Labels: source:gamemode, type:bug
