### ISSUE TITLE
trails in the shop are moved to the wrong place

### ISSUE THREAD

**Issue by Buckaduck** [redsunservers/LoadoutBugTracker#165] opened 2018-01-10 02:06 UTC
the trails in the shop are post to be in "player trails" but they are not for me and they are put in with "other items" heres a picture of the problem...
![well](https://user-images.githubusercontent.com/34257786/34752537-8391c9ec-f578-11e7-996c-6dcf5f792e3b.PNG)

not much else to say about it i didn't do shit to make this happen

**Comment by JustABLUToon** [comment] 2018-01-10 02:47
This issue was already brought up, and @EgocentricPoliceDick already said what the problem was.
Direct copy paste of what he said: 
"This will be addressed in a future update. Currently, the code which sorts items by category isn't in there for trails just yet."

**Closed** 2018-01-10 06:22 UTC
Labels: closed:duplicate

**Comment by ramunecarbonated** [comment] 2018-01-10 06:28
Duplicate of #160
