### ISSUE TITLE
SZF: Special Zombies that have increased max health don't actually have increased max health

### ISSUE THREAD

**Issue by itVictor** [redsunservers/LoadoutBugTracker#127] opened 2017-12-20 20:53 UTC
(unless it was stealthily changed)

this applies to stalkers so far, I'm assuming it also happens to kingpin and any other zombie that gets higher health than normal. I don't think it happens to the tank but will try to test that.

edit: to clarify they have the stock max health for their respective class

**Comment by ramunecarbonated** [comment] 2017-12-20 23:25
was intended but i actually forgot to document it

**Comment by ramunecarbonated** [comment] 2017-12-21 08:22
@koopa516 @Benoist3012 
For this issue, this is an undocumented inconsistensy.

**Comment by Benoist3012** [comment] 2017-12-21 14:41
what should be do then?

**Comment by ramunecarbonated** [comment] 2017-12-21 14:44
Remove references in-game where it says that special zombies have more health.

**Comment by itVictor** [comment] 2017-12-21 21:59
bumping this to say that the tank is also affected, he gets some overheal for killing players and such but his default HP is 300.

**Comment by ramunecarbonated** [comment] 2018-02-26 08:54
aiming to update szf soon with gameplay changes and try to address these.

**Comment by EgocentricPoliceDick** [comment] 2018-03-02 00:02
SZF updates are being pushed to a development branch which should fix this.
Closing.

**Closed by EgocentricPoliceDick** 2018-03-02 00:02 UTC
Labels: priority:low, source:gamemode, type:inconsistency
