### ISSUE TITLE
Name formatting breaks when mentioned and having 3 chat icons enabled

### ISSUE THREAD

**Issue by oWave** [redsunservers/LoadoutBugTracker#282] opened 2018-08-26 15:36 UTC
![image](https://user-images.githubusercontent.com/9253349/44629910-539ed580-a956-11e8-9213-0b70b75b8534.png)

Formatting works fine everywhere else like join messages.
Also works fine when either donator heart or flower gets turned of so it's not one of the icons causing it.

Namepaints do not cause the formatting issues. Even without a namepaint equiped the team color formatting does not work.

**Comment by EgocentricPoliceDick** [comment] 2018-08-26 15:54
Duplicate of #251, closing.

**Closed by EgocentricPoliceDick** 2018-08-26 15:54 UTC
