### ISSUE TITLE
Haunted Glow unusual effect may be broken for Pyros's "Muscle Power" Skin

### ISSUE THREAD

**Issue by GetJiggyWith1t** [redsunservers/LoadoutBugTracker#285] opened 2018-09-05 23:02 UTC
![screenshot 3](https://user-images.githubusercontent.com/42788069/45125382-0e7f5e00-b123-11e8-8dcf-b500b9629bcc.png)

![20180905174317_1](https://user-images.githubusercontent.com/42788069/45125447-60c07f00-b123-11e8-95ff-225109d48db4.jpg)

Since I unboxed it, I've never seen its effect. I also have asked people to tell me if they can see it, to check if it's client side, and no luck.

This is probably linked with #274 as EgocentricPoliceDick mentioned it had something to do with the particles.

**Comment by EgocentricPoliceDick** [comment] 2018-09-05 23:10
Duplicate of #274, closing.

**Closed by EgocentricPoliceDick** 2018-09-05 23:10 UTC
